function activeColumns = find_active_columns(encoded_tx_messages_estimate,survivingPaths,l,systemParameters,G)

activeColumns = [];
listSize = systemParameters.listSize;

for j=1:listSize
    A=survivingPaths{j,l-1};   % Surviving paths corr to jth root node until slot l-1
    for k=1:size(A,1)
        path=A(k,:); % Grab the kth path 
        pathMsgBits = fing_path_msg_bits(path,encoded_tx_messages_estimate,systemParameters); % message bits corresponding to this path
        permissibleParityBits=find_permissible_parity_bits(pathMsgBits,G{l}); % Compute parity bits generated by kth active path
        activeColumns=[activeColumns activeColumns_slotl(permissibleParityBits,l,systemParameters)];
    end
end
% Remove duplicates in activeColumns
activeColumns=unique(activeColumns);

end