function survivingPaths=tree_decoder_update_suriving_paths(survivingPaths,path,l,j,encoded_tx_messages_estimate,systemParameters,G)

A=survivingPaths{j,l};
pathMsgBits = fing_path_msg_bits(path,encoded_tx_messages_estimate,systemParameters); % message bits corresponding to this path
computedParityBits = find_permissible_parity_bits(pathMsgBits,G{l}); % Compute parity bits generated by message bits in this path

for k=1:size(encoded_tx_messages_estimate{l},1)
    % Verify if parity bits in kth child match with those generated by path
    index = parity_check(computedParityBits,k,l,encoded_tx_messages_estimate,systemParameters);
    if(index==1)
        % Update path if parity is satisfied
        new = [path k];
        A=[A;new];
    end
    
end

survivingPaths{j,l}=A;

end